format_version: v1.0
type: UniqueComponent
attributes: {id: ddr}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DDR_SIZE_MB}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '128'}
  - type: KeyValueSet
    attributes: {id: DDR_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '490', y: '120', id: ddr}
