package:
  format-version: "1.0.0"
  name: "gfx_apps_pic32mz_da"
  version: "v3.11.0"
  type: "application"
  status: "production"

  dependencies:
    - name: "gfx"
      type: "package"
      version: "v3.14.0"
    - name: "usb"
      type: "package"
      version: "v3.11.0"
