configName: glcd_rgba8888_mxt_mzda_intddr_round
folderName: legato_qs_mzda_round
format_version: v1.0
frameworkPath: ..\..\..\..\..
processor: PIC32MZ2064DAS176
projectName: legato_quickstart_mzda_round
settings:
  PackageFilter: audio;bsp;core;cryptoauthlib;csp;Devices;dev_packs;gfx;gfx-ed;harmony-services;net;quick_docs;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MZ-DA_DFP\1.4.118
